#This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_package 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.15, 3.12.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
    - name: Lint hAMRonization library with flake8
      run: |
        pushd hAMRonization
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics
        popd
    - name: Run sanity tests
      run: |
          pushd test 
          pytest
          popd
    - name: Run crude test of CLI parser for all tools
      run: |
          pushd test
          bash run_integration_test.sh
          popd
    #- name: Validate all harmonized .json files with SALAD schema
    #  run: |
    #    pip install schema_salad
    #    pushd test/data
    #    for f in *.harmonized.json; do schema-salad-tool ../../schema/antimicrobial_resistance_genomic_analysis_result.schema.yml ${f}; done
